version: '2'

services:

  market_db:
    image: redis:6-alpine
    volumes:
      - ./db:/data

  web:
    build: .
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://celery_broker:6379/0
      - CELERY_RESULT_BACKEND=redis://celery_broker:6379/0
      - DB_URL=redis://market_db:6379/0
    depends_on:
      - celery_broker
      - market_db

  invalidator:
    build: .
    command: bash -c 'while true; do python eddn_market_invalidator.py | tee logs/invalidator.log; sleep 1; done'
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=true
      - DB_URL=redis://market_db:6379/0
    depends_on:
      - web
      - market_db

  worker:
    build: .
    command: celery worker -A worker --loglevel=debug --logfile=logs/celery.log
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://celery_broker:6379/0
      - CELERY_RESULT_BACKEND=redis://celery_broker:6379/0
      - DB_URL=redis://market_db:6379/0
    depends_on:
      - web
      - celery_broker

  celery_broker:
    image: redis:6-alpine

  dashboard:
    build: .
    command: flower --app=worker.celery_worker --port=5555 --broker=redis://celery_broker:6379/0
    ports:
      - 5558:5555
    environment:
      - CELERY_BROKER_URL=redis://celery_broker:6379/0
      - CELERY_RESULT_BACKEND=redis://celery_broker:6379/0
    depends_on:
      - web
      - celery_broker
      - worker
