version: '2'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

  api:
    build: .
    ports:
      - 8004:8000
    command: uvicorn main:app --app-dir project --host 0.0.0.0 --reload
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`elite-sell.mancer.in`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"

  eddn:
    build: .
    command: bash -c 'while true; do python eddn_listener.py; done'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/

  edsm_dumps:
    build: .
    command: bash -c 'while true; do python station_dump.py; done'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/
