#!/bin/bash
while true
do
    clear
    curl -v -H "Content-type: application/json" -d@/tmp/request.json "https://elite-sell.mancer.in/sales" | \
        tee /tmp/last | \
        jq 'map({market, sale})' | \
        vim -
    sleep 2
done
